name: ros_nodes
description: A custom ros communication library for dart
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xmlrpc_server:
    git: https://github.com/supremehyo/xmlrpc_server.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
